[package]
version = "0.1.0"
name = "freivalds-precompile"
edition = "2021"

[dependencies]
alloy-sol-types = { workspace = true }
sp1-zkvm = "4.0.1"
lib = { path = "../lib" }
sp1-derive = "4.0.1"
blake3 = { version = "1.3.1", features = ["serde"] }