[package]
version = "0.1.0"
name = "fibonacci-program"
edition = "2021"

[dependencies]
alloy-sol-types = { workspace = true }
sp1-zkvm = { version = "4.0.1", features = ["embedded"] }
lib = { path = "../lib" }
sp1-derive = "4.0.1"
blake3 = { version = "1.3.1", features = ["serde"] }