[package]
name = "inner-product-precompile"
version = "1.0.0"
edition = "2021"
publish = false

[dependencies]

sp1-zkvm = { path = "./../../../sp1/crates/zkvm/entrypoint" }
sp1-derive = { path = "./../../../sp1/crates/derive" }